= Akaria RISC-V GNU toolchain

== About

This repository provides some makefiles to build GNU toolchains (binutils, GCC, C libraries) easily for NSITEXE Akaria RISC-V processors.

If you just want to use GNU toolchains, please download TAR archives from "releases" page.


== How to use

Just run "make install".
This command will download source codes from suitable repositories and configure and build automatically.
It will take long time (over an hour or more) and need large disk space (> 30GB).

[source,sh]
----
$ make install
----

You can specify a PARALLEL option to build more faster if you use multi-core CPU.
In this sample (PARALLEL=16) means that make will invoke up to 16 commands in parallel.


[source,sh]
----
$ make install PARALLEL=16
----

This command will generate some directories that has name "riscv64-*" if build procedures finished successfully.


== Toolchains

Currently this repository supports 3 toolchains.

* GCC with newlib
  ** Directory: riscv64-unknown-elf
  ** Arch: RV32 and RV64 (rv32i, rv32iac, rv32im, rv32imac, rv32imafc, rv64imac, rv64gc)
  ** Remarks: Standard C library for baremetal, not support pthreads
* GCC with GNU libc
  ** Directory: riscv64-unknown-linux-gnu
  ** Arch: RV32 and RV64 (rv32imac, rv32gc, rv64imac, rv64gc)
  ** Remarks: Full C library for Linux
* GCC with musl libc
  ** Directory: riscv64-unknown-linux-musl
  ** Arch: RV64 (rv64gc)
  ** Remarks: Full C library for Linux


== Release Build

Please refer xref:doc/release.adoc[Release Build] steps and Dockerfiles if you need release packages.


== Softwares and Licenses

If you want to know list of softwares and it's licenses, please refer xref:doc/software.adoc[Softwares].
